#ifndef TTGui_H
#define TTGui_H

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"
#include "StreamPlayer.hpp"
#include "SystemControl.hpp"

//// end generated include

/** Implementing MainFrame */
class TTGui : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnToggleCapture(wxCommandEvent& event);
		void OnToggleCorrection(wxCommandEvent& event);
		void OnFramePaint(wxPaintEvent& event);
		void OnClickExit(wxCommandEvent& event);
	public:
		StreamPlayer * player_p;
		SystemControl * sControl_p;
		/** Constructor */
		TTGui( wxWindow* parent );
	//// end generated class members
	
};

#endif // TTGui_H
