#ifndef TTGui_H
#define TTGui_H

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"
#include "wxStreamPlayer.hpp"
#include "SystemControl.hpp"

//// end generated include

/** Implementing MainFrame */
class TTGui : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnClickStart( wxCommandEvent& event );
		void OnClickExit( wxCommandEvent& event );
	public:
		wxStreamPlayer * player;
		SystemControl * sControl_p;
		/** Constructor */
		TTGui( wxWindow* parent );
	//// end generated class members
	
};

#endif // TTGui_H
